/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.lasercontroller;

import gnu.io.SerialPort;
import java.io.OutputStream;
import gnu.io.CommPortIdentifier;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.zu.ardulink.Link;
import org.zu.ardulink.gui.ConnectionPanel;
import org.zu.ardulink.gui.PWMController;

/**
 *
 * @author bernanos
 */
public class LaserController extends javax.swing.JFrame {
    
    // Global variables declaration
    SerialPort serialPort;
    private OutputStream output;
    private static final int TIME_OUT = 2000;
    private static final int DATA_RATE = 115200;

    /**
     * Creates new form LaserController
     */
    public LaserController() {
        initComponents();
        listPorts();
    }
    
    private void listPorts() {

            Enumeration portEnum = CommPortIdentifier.getPortIdentifiers();

            //First, Find an instance of serial port as set in PORT_NAMES.
            while (portEnum.hasMoreElements()) {
                    CommPortIdentifier currPortId = (CommPortIdentifier) portEnum.nextElement();
                    
                    portDropDown.addItem(currPortId.getName());
                    
            }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laserPanel1 = new javax.swing.JPanel();
        enable1 = new javax.swing.JRadioButton();
        slider1 = new javax.swing.JSlider();
        pwr1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnTest1 = new javax.swing.JToggleButton();
        freq1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        length1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnConnect = new javax.swing.JButton();
        portDropDown = new javax.swing.JComboBox<>();
        btnExec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        laserPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Laser 1"));

        enable1.setText("Enable");
        enable1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enable1ActionPerformed(evt);
            }
        });

        slider1.setOrientation(javax.swing.JSlider.VERTICAL);
        slider1.setEnabled(false);
        slider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider1StateChanged(evt);
            }
        });

        pwr1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pwr1.setText("0.0");
        pwr1.setEnabled(false);
        pwr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwr1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Power (%)");

        btnTest1.setText("TEST");
        btnTest1.setEnabled(false);
        btnTest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTest1ActionPerformed(evt);
            }
        });

        freq1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        freq1.setText("0");
        freq1.setEnabled(false);
        freq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freq1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Freq");

        length1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        length1.setText("0");
        length1.setEnabled(false);
        length1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                length1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Duration");

        javax.swing.GroupLayout laserPanel1Layout = new javax.swing.GroupLayout(laserPanel1);
        laserPanel1.setLayout(laserPanel1Layout);
        laserPanel1Layout.setHorizontalGroup(
            laserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laserPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(laserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(laserPanel1Layout.createSequentialGroup()
                        .addComponent(slider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(laserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2)
                            .addComponent(pwr1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(freq1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(length1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTest1)))
                    .addComponent(enable1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        laserPanel1Layout.setVerticalGroup(
            laserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laserPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enable1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(laserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(laserPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pwr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(freq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(length1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(btnTest1))
                    .addGroup(laserPanel1Layout.createSequentialGroup()
                        .addComponent(slider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        btnConnect.setText("Connect");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        btnExec.setText("Execute");
        btnExec.setEnabled(false);
        btnExec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(laserPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(portDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExec)
                            .addComponent(btnConnect))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(laserPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConnect))
                .addGap(18, 18, 18)
                .addComponent(btnExec)
                .addGap(218, 218, 218))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enable1ActionPerformed
        // TODO add your handling code here:
        if (enable1.isSelected()) {
            btnTest1.setEnabled(true);
            pwr1.setEnabled(true);
            freq1.setEnabled(true);
            length1.setEnabled(true);
            slider1.setEnabled(true);
            int pwr = slider1.getValue();
            pwr1.setText(String.valueOf(pwr));
        } else {
            btnTest1.setEnabled(false);
            pwr1.setEnabled(false);
            freq1.setEnabled(false);
            length1.setEnabled(false);
            slider1.setEnabled(false);
        }   
    }//GEN-LAST:event_enable1ActionPerformed

    private void btnTest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTest1ActionPerformed
        // TODO add your handling code here:
        if (btnTest1.isSelected()){
            System.out.println("Laser ON");
            // Sent message to arduino to switch laser 1 ON
            int pwr = Integer.parseInt(pwr1.getText());
            int dur = Integer.parseInt(length1.getText());
            int freq = Integer.parseInt(freq1.getText());
            String message = String.format("T,%d,%d,%d,%d,%d,", 1, 1, pwr, dur, freq);
            sendData(message);
        } else {
            System.out.println("Laser OFF");
            // Send message to arduino to swich laser 1 OFF
            String message = "O,1,0,0,0,0,";
            sendData(message);
        }
    }//GEN-LAST:event_btnTest1ActionPerformed

    private void slider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider1StateChanged
        // TODO add your handling code here:
        if (btnTest1.isSelected()){
            int pwr = slider1.getValue();
            pwr1.setText(String.valueOf(pwr));
            int dur = Integer.parseInt(length1.getText());
            int freq = Integer.parseInt(freq1.getText());
            String message = String.format("T,%d,%d,%d,%d,%d,", 1, 1, pwr, dur, freq);
            sendData(message);
        } else {
            int pwr = slider1.getValue();
            pwr1.setText(String.valueOf(pwr));
        }
    }//GEN-LAST:event_slider1StateChanged

    private void pwr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwr1ActionPerformed
        // TODO add your handling code here:
        if (btnTest1.isSelected()){
            int pwr = Integer.parseInt(pwr1.getText());
            slider1.setValue(pwr);
            int dur = Integer.parseInt(length1.getText());
            int freq = Integer.parseInt(freq1.getText());
            String message = String.format("T,%d,%d,%d,%d,%d,", 1, 1, pwr, dur, freq);
            sendData(message);
        } else {
            int pwr = Integer.parseInt(pwr1.getText());
            slider1.setValue(pwr);
        }
    }//GEN-LAST:event_pwr1ActionPerformed

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        // TODO add your handling code here:
        
        if (btnConnect.getText().equals("Connect")) {
            // Get port and baud rate from connection panel
            CommPortIdentifier portId = null;
            Enumeration portEnum = CommPortIdentifier.getPortIdentifiers();

            String selectedPort = portDropDown.getSelectedItem().toString();

            while (portEnum.hasMoreElements()) {

                CommPortIdentifier currPortId = (CommPortIdentifier) portEnum.nextElement();
                if (currPortId.getName().equals(selectedPort)) {
                    portId = currPortId;
                    System.out.println("Port found...");
                    break;
                }
            }
            if (portId == null) {
                System.out.println("Could not find COM port.");
                return;
            }

            try {
                    // open serial port, and use class name for the appName.
                    //First, Find an instance of serial port as set in PORT_NAMES.

                    serialPort = (SerialPort) portId.open(this.getClass().getName(),
                                    TIME_OUT);

                    // set port parameters
                    serialPort.setSerialPortParams(DATA_RATE,
                                    SerialPort.DATABITS_8,
                                    SerialPort.STOPBITS_1,
                                    SerialPort.PARITY_NONE);

                    // open the streams
                    //input = new BufferedReader(new InputStreamReader(serialPort.getInputStream()));
                    output = new PrintStream(serialPort.getOutputStream(), true);

                    // add event listeners
                    //serialPort.addEventListener(this);
                    //serialPort.notifyOnDataAvailable(true);
                    System.out.println("Connected...");
                    btnConnect.setText("Disconnect");
                    btnExec.setEnabled(true);

            } catch (Exception e) {
                System.out.println("Could not connect...");
                System.err.println(e.toString());
            }
        } else if (btnConnect.getText().equals("Disconnect")) {
            if (serialPort != null) {
                serialPort.removeEventListener();
                serialPort.close();
                System.out.println("Disonnected...");
                btnConnect.setText("Connect");
                btnExec.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnConnectActionPerformed

    private void freq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freq1ActionPerformed
        // TODO add your handling code here:
        if (btnTest1.isSelected()){
            int pwr = Integer.parseInt(pwr1.getText());
            slider1.setValue(pwr);
            int dur = Integer.parseInt(length1.getText());
            int freq = Integer.parseInt(freq1.getText());
            String message = String.format("T,%d,%d,%d,%d,%d,", 1, 1, pwr, dur, freq);
            sendData(message);
        } 
    }//GEN-LAST:event_freq1ActionPerformed

    private void length1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_length1ActionPerformed
        // TODO add your handling code here:
        if (btnTest1.isSelected()){
            int pwr = Integer.parseInt(pwr1.getText());
            slider1.setValue(pwr);
            int dur = Integer.parseInt(length1.getText());
            int freq = Integer.parseInt(freq1.getText());
            String message = String.format("T,%d,%d,%d,%d,%d,", 1, 1, pwr, dur, freq);
            sendData(message);
        }
    }//GEN-LAST:event_length1ActionPerformed

    private void btnExecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecActionPerformed
        // TODO add your handling code here:
        if(btnExec.getText() == "Execute") {
            String message = "E,";
            sendData(message);
            btnExec.setText("Stop");
        } else {
            String message = "O,";
            sendData(message);
            btnExec.setText("Execute");
        }
    }//GEN-LAST:event_btnExecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaserController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaserController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaserController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaserController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LaserController().setVisible(true);
            }
        });
    }
    
    public void setupSystemp(){
        /**
         * Will iterate through each laser and send respective parameters
         * including the paradigm for each channel.
         * Should receive a confirmation from Arduino
         */
        String message = "message";
    }
    
    public void sendData(String message){
        if(output != null){
            try {
                // Add code to send data
                System.out.println(message);
                output.write(message.getBytes());
                //output.flush();
            } catch (IOException ex) {
                System.out.println("Could not send message...");
                Logger.getLogger(LaserController.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnExec;
    private javax.swing.JToggleButton btnTest1;
    private javax.swing.JRadioButton enable1;
    private javax.swing.JTextField freq1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel laserPanel1;
    private javax.swing.JTextField length1;
    private javax.swing.JComboBox<String> portDropDown;
    private javax.swing.JTextField pwr1;
    private javax.swing.JSlider slider1;
    // End of variables declaration//GEN-END:variables
}
