/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.lasercontroller;

import gnu.io.SerialPort;
import java.io.OutputStream;
import gnu.io.CommPortIdentifier;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.zu.ardulink.Link;
import org.zu.ardulink.gui.ConnectionPanel;
import org.zu.ardulink.gui.PWMController;
import java.util.Iterator;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
 
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author bernanos
 */
public class LaserController extends javax.swing.JFrame {
    
    // Global variables declaration
    SerialPort serialPort;
    private OutputStream output;
    private static final int TIME_OUT = 2000;
    private static final int DATA_RATE = 115200;
    private static JFileChooser fileChooser = new JFileChooser();

    /**
     * Creates new form LaserController
     */
    public LaserController() {
        initComponents();
        listPorts();
    }
    
    private void listPorts() {

            Enumeration portEnum = CommPortIdentifier.getPortIdentifiers();

            //First, Find an instance of serial port as set in PORT_NAMES.
            while (portEnum.hasMoreElements()) {
                    CommPortIdentifier currPortId = (CommPortIdentifier) portEnum.nextElement();
                    
                    portDropDown.addItem(currPortId.getName());
                    
            }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laserPanel1 = new javax.swing.JPanel();
        enable1 = new javax.swing.JRadioButton();
        btnTest1 = new javax.swing.JToggleButton();
        freq1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        duration1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnCal1 = new javax.swing.JToggleButton();
        laserPanel2 = new javax.swing.JPanel();
        enable2 = new javax.swing.JRadioButton();
        btnTest2 = new javax.swing.JToggleButton();
        freq2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        duration2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnCal2 = new javax.swing.JToggleButton();
        laserPanel3 = new javax.swing.JPanel();
        enable3 = new javax.swing.JRadioButton();
        btnTest3 = new javax.swing.JToggleButton();
        freq3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        duration3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnCal3 = new javax.swing.JToggleButton();
        laserPanel4 = new javax.swing.JPanel();
        enable4 = new javax.swing.JRadioButton();
        btnTest4 = new javax.swing.JToggleButton();
        freq4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        duration4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnCal4 = new javax.swing.JToggleButton();
        laserPanel5 = new javax.swing.JPanel();
        enable5 = new javax.swing.JRadioButton();
        btnTest5 = new javax.swing.JToggleButton();
        freq5 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        duration5 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnCal5 = new javax.swing.JToggleButton();
        laserPanel6 = new javax.swing.JPanel();
        enable6 = new javax.swing.JRadioButton();
        btnTest6 = new javax.swing.JToggleButton();
        freq6 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        duration6 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btnCal6 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        nOfScans = new javax.swing.JTextField();
        dummiesField = new javax.swing.JTextField();
        trField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        portDropDown = new javax.swing.JComboBox<>();
        btnConnect = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnExec = new javax.swing.JButton();
        btnUpload = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuOpenItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        laserPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Laser 1"));

        enable1.setText("Enable");
        enable1.setEnabled(false);
        enable1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enable1ActionPerformed(evt);
            }
        });

        btnTest1.setText("TEST");
        btnTest1.setEnabled(false);
        btnTest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTest1ActionPerformed(evt);
            }
        });

        freq1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        freq1.setText("10");
        freq1.setEnabled(false);
        freq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freq1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Freq");

        duration1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        duration1.setText("10");
        duration1.setEnabled(false);
        duration1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duration1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Duration");

        btnCal1.setText("Calibrate");
        btnCal1.setEnabled(false);
        btnCal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCal1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout laserPanel1Layout = new javax.swing.GroupLayout(laserPanel1);
        laserPanel1.setLayout(laserPanel1Layout);
        laserPanel1Layout.setHorizontalGroup(
            laserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laserPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(laserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTest1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(laserPanel1Layout.createSequentialGroup()
                        .addGroup(laserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enable1)
                            .addGroup(laserPanel1Layout.createSequentialGroup()
                                .addGroup(laserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(freq1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(duration1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(laserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnCal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        laserPanel1Layout.setVerticalGroup(
            laserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laserPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enable1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(laserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(freq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(laserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(duration1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTest1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCal1)
                .addContainerGap())
        );

        laserPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Laser 2"));

        enable2.setText("Enable");
        enable2.setEnabled(false);
        enable2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enable2ActionPerformed(evt);
            }
        });

        btnTest2.setText("TEST");
        btnTest2.setEnabled(false);
        btnTest2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTest2ActionPerformed(evt);
            }
        });

        freq2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        freq2.setText("10");
        freq2.setEnabled(false);
        freq2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freq2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Freq");

        duration2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        duration2.setText("10");
        duration2.setEnabled(false);
        duration2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duration2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Duration");

        btnCal2.setText("Calibrate");
        btnCal2.setEnabled(false);
        btnCal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCal2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout laserPanel2Layout = new javax.swing.GroupLayout(laserPanel2);
        laserPanel2.setLayout(laserPanel2Layout);
        laserPanel2Layout.setHorizontalGroup(
            laserPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laserPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(laserPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTest2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(laserPanel2Layout.createSequentialGroup()
                        .addGroup(laserPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enable2)
                            .addGroup(laserPanel2Layout.createSequentialGroup()
                                .addGroup(laserPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(freq2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(duration2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(laserPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnCal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        laserPanel2Layout.setVerticalGroup(
            laserPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laserPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enable2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(laserPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(freq2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(laserPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(duration2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTest2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCal2)
                .addContainerGap())
        );

        laserPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Laser 3"));

        enable3.setText("Enable");
        enable3.setEnabled(false);
        enable3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enable3ActionPerformed(evt);
            }
        });

        btnTest3.setText("TEST");
        btnTest3.setEnabled(false);
        btnTest3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTest3ActionPerformed(evt);
            }
        });

        freq3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        freq3.setText("10");
        freq3.setEnabled(false);
        freq3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freq3ActionPerformed(evt);
            }
        });

        jLabel13.setText("Freq");

        duration3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        duration3.setText("10");
        duration3.setEnabled(false);
        duration3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duration3ActionPerformed(evt);
            }
        });

        jLabel14.setText("Duration");

        btnCal3.setText("Calibrate");
        btnCal3.setEnabled(false);
        btnCal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCal3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout laserPanel3Layout = new javax.swing.GroupLayout(laserPanel3);
        laserPanel3.setLayout(laserPanel3Layout);
        laserPanel3Layout.setHorizontalGroup(
            laserPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laserPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(laserPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTest3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(laserPanel3Layout.createSequentialGroup()
                        .addGroup(laserPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enable3)
                            .addGroup(laserPanel3Layout.createSequentialGroup()
                                .addGroup(laserPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(freq3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(duration3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(laserPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnCal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        laserPanel3Layout.setVerticalGroup(
            laserPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laserPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enable3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(laserPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(freq3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(laserPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(duration3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTest3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCal3)
                .addContainerGap())
        );

        laserPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Laser 4"));

        enable4.setText("Enable");
        enable4.setEnabled(false);
        enable4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enable4ActionPerformed(evt);
            }
        });

        btnTest4.setText("TEST");
        btnTest4.setEnabled(false);
        btnTest4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTest4ActionPerformed(evt);
            }
        });

        freq4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        freq4.setText("10");
        freq4.setEnabled(false);
        freq4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freq4ActionPerformed(evt);
            }
        });

        jLabel15.setText("Freq");

        duration4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        duration4.setText("10");
        duration4.setEnabled(false);
        duration4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duration4ActionPerformed(evt);
            }
        });

        jLabel16.setText("Duration");

        btnCal4.setText("Calibrate");
        btnCal4.setEnabled(false);
        btnCal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCal4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout laserPanel4Layout = new javax.swing.GroupLayout(laserPanel4);
        laserPanel4.setLayout(laserPanel4Layout);
        laserPanel4Layout.setHorizontalGroup(
            laserPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laserPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(laserPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTest4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(laserPanel4Layout.createSequentialGroup()
                        .addGroup(laserPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enable4)
                            .addGroup(laserPanel4Layout.createSequentialGroup()
                                .addGroup(laserPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(freq4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(duration4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(laserPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnCal4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        laserPanel4Layout.setVerticalGroup(
            laserPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laserPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enable4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(laserPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(freq4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(laserPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(duration4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTest4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCal4)
                .addContainerGap())
        );

        laserPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Laser 5"));

        enable5.setText("Enable");
        enable5.setEnabled(false);
        enable5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enable5ActionPerformed(evt);
            }
        });

        btnTest5.setText("TEST");
        btnTest5.setEnabled(false);
        btnTest5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTest5ActionPerformed(evt);
            }
        });

        freq5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        freq5.setText("10");
        freq5.setEnabled(false);
        freq5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freq5ActionPerformed(evt);
            }
        });

        jLabel17.setText("Freq");

        duration5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        duration5.setText("10");
        duration5.setEnabled(false);
        duration5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duration5ActionPerformed(evt);
            }
        });

        jLabel18.setText("Duration");

        btnCal5.setText("Calibrate");
        btnCal5.setEnabled(false);
        btnCal5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCal5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout laserPanel5Layout = new javax.swing.GroupLayout(laserPanel5);
        laserPanel5.setLayout(laserPanel5Layout);
        laserPanel5Layout.setHorizontalGroup(
            laserPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laserPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(laserPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTest5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(laserPanel5Layout.createSequentialGroup()
                        .addGroup(laserPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enable5)
                            .addGroup(laserPanel5Layout.createSequentialGroup()
                                .addGroup(laserPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(freq5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(duration5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(laserPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnCal5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        laserPanel5Layout.setVerticalGroup(
            laserPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laserPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enable5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(laserPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(freq5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(laserPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(duration5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTest5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCal5)
                .addContainerGap())
        );

        laserPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Laser 6"));

        enable6.setText("Enable");
        enable6.setEnabled(false);
        enable6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enable6ActionPerformed(evt);
            }
        });

        btnTest6.setText("TEST");
        btnTest6.setEnabled(false);
        btnTest6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTest6ActionPerformed(evt);
            }
        });

        freq6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        freq6.setText("10");
        freq6.setEnabled(false);
        freq6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freq6ActionPerformed(evt);
            }
        });

        jLabel19.setText("Freq");

        duration6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        duration6.setText("10");
        duration6.setEnabled(false);
        duration6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duration6ActionPerformed(evt);
            }
        });

        jLabel20.setText("Duration");

        btnCal6.setText("Calibrate");
        btnCal6.setEnabled(false);
        btnCal6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCal6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout laserPanel6Layout = new javax.swing.GroupLayout(laserPanel6);
        laserPanel6.setLayout(laserPanel6Layout);
        laserPanel6Layout.setHorizontalGroup(
            laserPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laserPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(laserPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTest6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(laserPanel6Layout.createSequentialGroup()
                        .addGroup(laserPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enable6)
                            .addGroup(laserPanel6Layout.createSequentialGroup()
                                .addGroup(laserPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(freq6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(duration6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(laserPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnCal6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        laserPanel6Layout.setVerticalGroup(
            laserPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laserPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enable6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(laserPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(freq6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(laserPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(duration6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTest6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCal6)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Scanner Parameters"));

        nOfScans.setEditable(false);
        nOfScans.setText("0");

        dummiesField.setText("0");

        trField.setText("1000");

        jLabel1.setText("Number of scans");

        jLabel2.setText("Number of dummies");

        jLabel3.setText("TR in miliseconds");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nOfScans)
                    .addComponent(dummiesField)
                    .addComponent(trField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nOfScans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dummiesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Arduino Connection"));

        portDropDown.setMaximumRowCount(16);
        portDropDown.setToolTipText("");

        btnConnect.setText("Connect");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(btnConnect)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(portDropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(portDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConnect)
                .addGap(22, 22, 22))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Execution Control"));

        btnExec.setBackground(new java.awt.Color(204, 204, 204));
        btnExec.setText("Execute");
        btnExec.setEnabled(false);
        btnExec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecActionPerformed(evt);
            }
        });

        btnUpload.setText("UPLOAD");
        btnUpload.setEnabled(false);
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExec, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnUpload)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("File");

        menuOpenItem.setText("Open");
        menuOpenItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpenItemActionPerformed(evt);
            }
        });
        jMenu1.add(menuOpenItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(laserPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(laserPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(laserPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(laserPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(laserPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laserPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(laserPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laserPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laserPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laserPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laserPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laserPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        laserPanel1.getAccessibleContext().setAccessibleName("Laser 2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        // TODO add your handling code here:
        
        if (btnConnect.getText().equals("Connect")) {
            // Get port and baud rate from connection panel
            CommPortIdentifier portId = null;
            Enumeration portEnum = CommPortIdentifier.getPortIdentifiers();

            String selectedPort = portDropDown.getSelectedItem().toString();

            while (portEnum.hasMoreElements()) {

                CommPortIdentifier currPortId = (CommPortIdentifier) portEnum.nextElement();
                if (currPortId.getName().equals(selectedPort)) {
                    portId = currPortId;
                    System.out.println("Port found...");
                    break;
                }
            }
            if (portId == null) {
                System.out.println("Could not find COM port.");
                return;
            }

            try {
                    // open serial port, and use class name for the appName.
                    //First, Find an instance of serial port as set in PORT_NAMES.

                    serialPort = (SerialPort) portId.open(this.getClass().getName(),
                                    TIME_OUT);

                    // set port parameters
                    serialPort.setSerialPortParams(DATA_RATE,
                                    SerialPort.DATABITS_8,
                                    SerialPort.STOPBITS_1,
                                    SerialPort.PARITY_NONE);

                    // open the streams
                    //input = new BufferedReader(new InputStreamReader(serialPort.getInputStream()));
                    output = new PrintStream(serialPort.getOutputStream(), true);

                    // add event listeners
                    //serialPort.addEventListener(this);
                    //serialPort.notifyOnDataAvailable(true);
                    System.out.println("Connected...");
                    btnConnect.setText("Disconnect");
                    btnExec.setEnabled(true);
                    enable1.setEnabled(true);
                    enable2.setEnabled(true);
                    enable3.setEnabled(true);
                    enable4.setEnabled(true);
                    enable5.setEnabled(true);
                    enable6.setEnabled(true);

            } catch (Exception e) {
                System.out.println("Could not connect...");
                System.err.println(e.toString());
            }
        } else if (btnConnect.getText().equals("Disconnect")) {
            if (serialPort != null) {
                serialPort.removeEventListener();
                serialPort.close();
                System.out.println("Disonnected...");
                btnConnect.setText("Connect");
                btnExec.setEnabled(false);
                enable1.setEnabled(false);
                enable2.setEnabled(false);
                // Write code to disable all objects once disconnected
                enable3.setEnabled(false);
                enable4.setEnabled(false);
                enable5.setEnabled(false);
                enable6.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnConnectActionPerformed

    private void btnExecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecActionPerformed
        // TODO add your handling code here:
        if(btnExec.getText() == "Execute") {
            String message = "E,";
            sendData(message);
            btnExec.setText("Stop");
        } else {
            String message = "O,";
            sendData(message);
            btnExec.setText("Execute");
        }
    }//GEN-LAST:event_btnExecActionPerformed

    private void duration1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duration1ActionPerformed
        // TODO add your handling code here:
        if (btnTest1.isSelected()){
            int dur = Integer.parseInt(duration1.getText());
            int freq = Integer.parseInt(freq1.getText());
            String message = String.format("T,%d,%d,%d,%d,", 1, 1, dur, freq);
            sendData(message);
        }
    }//GEN-LAST:event_duration1ActionPerformed

    private void btnTest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTest1ActionPerformed
        // TODO add your handling code here:
        if (btnTest1.isSelected()){
            System.out.println("Laser1 ON");
            // Sent message to arduino to switch laser 1 ON
            int dur = Integer.parseInt(duration1.getText());
            int freq = Integer.parseInt(freq1.getText());
            String message = String.format("T,%d,%d,%d,%d,", 1, 1, dur, freq);
            sendData(message);
        } else {
            System.out.println("Laser1 OFF");
            // Send message to arduino to swich laser 1 OFF
            String message = "T,1,0,0,0,";
            sendData(message);
        }
    }//GEN-LAST:event_btnTest1ActionPerformed

    private void enable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enable1ActionPerformed
        // TODO add your handling code here:
        if (enable1.isSelected()) {
            btnTest1.setEnabled(true);
            freq1.setEnabled(true);
            duration1.setEnabled(true);
            btnCal1.setEnabled(true);
        } else {
            btnTest1.setEnabled(false);
            freq1.setEnabled(false);
            duration1.setEnabled(false);
            btnCal1.setEnabled(false);
        }
    }//GEN-LAST:event_enable1ActionPerformed

    private void freq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freq1ActionPerformed
        // TODO add your handling code here:
        if (btnTest1.isSelected()){
            int dur = Integer.parseInt(duration1.getText());
            int freq = Integer.parseInt(freq1.getText());
            String message = String.format("T,%d,%d,%d,%d,", 1, 1, dur, freq);
            sendData(message);
        }
    }//GEN-LAST:event_freq1ActionPerformed

    private void btnCal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCal1ActionPerformed
        // TODO add your handling code here:
        if (btnCal1.isSelected()){
            String message = "C,1,1,";
            sendData(message);
        } else {
            String message = "C,1,0,";
            sendData(message);
        }
    }//GEN-LAST:event_btnCal1ActionPerformed

    private void enable2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enable2ActionPerformed
        // TODO add your handling code here:
        if (enable2.isSelected()) {
            btnTest2.setEnabled(true);
            freq2.setEnabled(true);
            duration2.setEnabled(true);
            btnCal2.setEnabled(true);
        } else {
            btnTest2.setEnabled(false);
            freq2.setEnabled(false);
            duration2.setEnabled(false);
            btnCal2.setEnabled(false);
        }
    }//GEN-LAST:event_enable2ActionPerformed

    private void btnTest2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTest2ActionPerformed
        // TODO add your handling code here:
        if (btnTest2.isSelected()){
            System.out.println("Laser2 ON");
            // Sent message to arduino to switch laser 1 ON
            int dur = Integer.parseInt(duration2.getText());
            int freq = Integer.parseInt(freq2.getText());
            String message = String.format("T,%d,%d,%d,%d,", 2, 1, dur, freq);
            sendData(message);
        } else {
            System.out.println("Laser2 OFF");
            // Send message to arduino to swich laser 1 OFF
            String message = "T,2,0,0,0,";
            sendData(message);
        }
    }//GEN-LAST:event_btnTest2ActionPerformed

    private void freq2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freq2ActionPerformed
        // TODO add your handling code here:
        if (btnTest2.isSelected()){
            int dur = Integer.parseInt(duration2.getText());
            int freq = Integer.parseInt(freq2.getText());
            String message = String.format("T,%d,%d,%d,%d,", 2, 1, dur, freq);
            sendData(message);
        }
    }//GEN-LAST:event_freq2ActionPerformed

    private void duration2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duration2ActionPerformed
        // TODO add your handling code here:
        if (btnTest2.isSelected()){
            int dur = Integer.parseInt(duration2.getText());
            int freq = Integer.parseInt(freq2.getText());
            String message = String.format("T,%d,%d,%d,%d,", 2, 1, dur, freq);
            sendData(message);
        }
    }//GEN-LAST:event_duration2ActionPerformed

    private void btnCal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCal2ActionPerformed
        // TODO add your handling code here:
        if (btnCal2.isSelected()){
            String message = "C,2,1,";
            sendData(message);
        } else {
            String message = "C,2,0,";
            sendData(message);
        }
    }//GEN-LAST:event_btnCal2ActionPerformed

    private void enable3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enable3ActionPerformed
        // TODO add your handling code here:
        if (enable3.isSelected()) {
            btnTest3.setEnabled(true);
            freq3.setEnabled(true);
            duration3.setEnabled(true);
            btnCal3.setEnabled(true);
        } else {
            btnTest3.setEnabled(false);
            freq3.setEnabled(false);
            duration3.setEnabled(false);
            btnCal3.setEnabled(false);
        }
    }//GEN-LAST:event_enable3ActionPerformed

    private void btnTest3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTest3ActionPerformed
        // TODO add your handling code here:
        if (btnTest3.isSelected()){
            System.out.println("Laser3 ON");
            // Sent message to arduino to switch laser 1 ON
            int dur = Integer.parseInt(duration3.getText());
            int freq = Integer.parseInt(freq3.getText());
            String message = String.format("T,%d,%d,%d,%d,", 3, 1, dur, freq);
            sendData(message);
        } else {
            System.out.println("Laser3 OFF");
            // Send message to arduino to swich laser 1 OFF
            String message = "T,3,0,0,0,";
            sendData(message);
        }
    }//GEN-LAST:event_btnTest3ActionPerformed

    private void freq3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freq3ActionPerformed
        // TODO add your handling code here:
        if (btnTest3.isSelected()){
            int dur = Integer.parseInt(duration3.getText());
            int freq = Integer.parseInt(freq3.getText());
            String message = String.format("T,%d,%d,%d,%d,", 3, 1, dur, freq);
            sendData(message);
        }
    }//GEN-LAST:event_freq3ActionPerformed

    private void duration3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duration3ActionPerformed
        // TODO add your handling code here:
        if (btnTest3.isSelected()){
            int dur = Integer.parseInt(duration3.getText());
            int freq = Integer.parseInt(freq3.getText());
            String message = String.format("T,%d,%d,%d,%d,", 3, 1, dur, freq);
            sendData(message);
        }
    }//GEN-LAST:event_duration3ActionPerformed

    private void btnCal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCal3ActionPerformed
        // TODO add your handling code here:
        if (btnCal3.isSelected()){
            String message = "C,3,1,";
            sendData(message);
        } else {
            String message = "C,3,0,";
            sendData(message);
        }
    }//GEN-LAST:event_btnCal3ActionPerformed

    private void enable4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enable4ActionPerformed
        // TODO add your handling code here:
        if (enable4.isSelected()) {
            btnTest4.setEnabled(true);
            freq4.setEnabled(true);
            duration4.setEnabled(true);
            btnCal4.setEnabled(true);
        } else {
            btnTest4.setEnabled(false);
            freq4.setEnabled(false);
            duration4.setEnabled(false);
            btnCal4.setEnabled(false);
        }
    }//GEN-LAST:event_enable4ActionPerformed

    private void btnTest4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTest4ActionPerformed
        // TODO add your handling code here:
        if (btnTest4.isSelected()){
            System.out.println("Laser4 ON");
            // Sent message to arduino to switch laser 1 ON
            int dur = Integer.parseInt(duration4.getText());
            int freq = Integer.parseInt(freq4.getText());
            String message = String.format("T,%d,%d,%d,%d,", 4, 1, dur, freq);
            sendData(message);
        } else {
            System.out.println("Laser4 OFF");
            // Send message to arduino to swich laser 1 OFF
            String message = "T,4,0,0,0,";
            sendData(message);
        }
    }//GEN-LAST:event_btnTest4ActionPerformed

    private void freq4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freq4ActionPerformed
        // TODO add your handling code here:
        if (btnTest4.isSelected()){
            int dur = Integer.parseInt(duration4.getText());
            int freq = Integer.parseInt(freq4.getText());
            String message = String.format("T,%d,%d,%d,%d,", 4, 1, dur, freq);
            sendData(message);
        }
    }//GEN-LAST:event_freq4ActionPerformed

    private void duration4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duration4ActionPerformed
        // TODO add your handling code here:
        if (btnTest4.isSelected()){
            int dur = Integer.parseInt(duration4.getText());
            int freq = Integer.parseInt(freq4.getText());
            String message = String.format("T,%d,%d,%d,%d,", 4, 1, dur, freq);
            sendData(message);
        }
    }//GEN-LAST:event_duration4ActionPerformed

    private void btnCal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCal4ActionPerformed
        // TODO add your handling code here:
        if (btnCal4.isSelected()){
            String message = "C,4,1,";
            sendData(message);
        } else {
            String message = "C,4,0,";
            sendData(message);
        }
    }//GEN-LAST:event_btnCal4ActionPerformed

    private void enable5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enable5ActionPerformed
        // TODO add your handling code here:
        if (enable5.isSelected()) {
            btnTest5.setEnabled(true);
            freq5.setEnabled(true);
            duration5.setEnabled(true);
            btnCal5.setEnabled(true);
        } else {
            btnTest5.setEnabled(false);
            freq5.setEnabled(false);
            duration5.setEnabled(false);
            btnCal5.setEnabled(false);
        }
    }//GEN-LAST:event_enable5ActionPerformed

    private void btnTest5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTest5ActionPerformed
        // TODO add your handling code here:
        if (btnTest5.isSelected()){
            System.out.println("Laser5 ON");
            // Sent message to arduino to switch laser 1 ON
            int dur = Integer.parseInt(duration5.getText());
            int freq = Integer.parseInt(freq5.getText());
            String message = String.format("T,%d,%d,%d,%d,", 5, 1, dur, freq);
            sendData(message);
        } else {
            System.out.println("Laser5 OFF");
            // Send message to arduino to swich laser 1 OFF
            String message = "T,5,0,0,0,";
            sendData(message);
        }
    }//GEN-LAST:event_btnTest5ActionPerformed

    private void freq5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freq5ActionPerformed
        // TODO add your handling code here:
        if (btnTest5.isSelected()){
            int dur = Integer.parseInt(duration5.getText());
            int freq = Integer.parseInt(freq5.getText());
            String message = String.format("T,%d,%d,%d,%d,", 5, 1, dur, freq);
            sendData(message);
        }
    }//GEN-LAST:event_freq5ActionPerformed

    private void duration5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duration5ActionPerformed
        // TODO add your handling code here:
        if (btnTest5.isSelected()){
            int dur = Integer.parseInt(duration5.getText());
            int freq = Integer.parseInt(freq5.getText());
            String message = String.format("T,%d,%d,%d,%d,", 5, 1, dur, freq);
            sendData(message);
        }
    }//GEN-LAST:event_duration5ActionPerformed

    private void btnCal5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCal5ActionPerformed
        // TODO add your handling code here:
        if (btnCal5.isSelected()){
            String message = "C,5,1,";
            sendData(message);
        } else {
            String message = "C,5,0,";
            sendData(message);
        }
    }//GEN-LAST:event_btnCal5ActionPerformed

    private void enable6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enable6ActionPerformed
        // TODO add your handling code here:
        if (enable6.isSelected()) {
            btnTest6.setEnabled(true);
            freq6.setEnabled(true);
            duration6.setEnabled(true);
            btnCal6.setEnabled(true);
        } else {
            btnTest6.setEnabled(false);
            freq6.setEnabled(false);
            duration6.setEnabled(false);
            btnCal6.setEnabled(false);
        }
    }//GEN-LAST:event_enable6ActionPerformed

    private void btnTest6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTest6ActionPerformed
        // TODO add your handling code here:
        if (btnTest6.isSelected()){
            System.out.println("Laser6 ON");
            // Sent message to arduino to switch laser 1 ON
            int dur = Integer.parseInt(duration6.getText());
            int freq = Integer.parseInt(freq6.getText());
            String message = String.format("T,%d,%d,%d,%d,", 6, 1, dur, freq);
            sendData(message);
        } else {
            System.out.println("Laser6 OFF");
            // Send message to arduino to swich laser 1 OFF
            String message = "T,6,0,0,0,";
            sendData(message);
        }
    }//GEN-LAST:event_btnTest6ActionPerformed

    private void freq6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freq6ActionPerformed
        // TODO add your handling code here:
        if (btnTest6.isSelected()){
            int dur = Integer.parseInt(duration6.getText());
            int freq = Integer.parseInt(freq6.getText());
            String message = String.format("T,%d,%d,%d,%d,", 6, 1, dur, freq);
            sendData(message);
        }
    }//GEN-LAST:event_freq6ActionPerformed

    private void duration6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duration6ActionPerformed
        // TODO add your handling code here:
        if (btnTest6.isSelected()){
            int dur = Integer.parseInt(duration6.getText());
            int freq = Integer.parseInt(freq6.getText());
            String message = String.format("T,%d,%d,%d,%d,", 6, 1, dur, freq);
            sendData(message);
        }
    }//GEN-LAST:event_duration6ActionPerformed

    private void btnCal6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCal6ActionPerformed
        // TODO add your handling code here:
        if (btnCal6.isSelected()){
            String message = "C,6,1,";
            sendData(message);
        } else {
            String message = "C,6,0,";
            sendData(message);
        }
    }//GEN-LAST:event_btnCal6ActionPerformed

    private void menuOpenItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpenItemActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());

        int returnValue = jfc.showOpenDialog(null);
        // int returnValue = jfc.showSaveDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            try {
                File selectedFile = jfc.getSelectedFile();
                System.out.println(selectedFile.getAbsolutePath());
                readExcel(selectedFile.getAbsolutePath());
            } catch (IOException ex) {
                Logger.getLogger(LaserController.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_menuOpenItemActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUploadActionPerformed

    public void readExcel(String fileName) throws IOException {
        try {

            FileInputStream excelFile = new FileInputStream(new File(fileName));
            Workbook workbook = new HSSFWorkbook(excelFile);
            Sheet datatypeSheet = workbook.getSheetAt(0);
            Iterator<Row> iterator = datatypeSheet.iterator();
            
            int nor = datatypeSheet.getLastRowNum();
            nOfScans.setText(Integer.toString(nor+1));
            System.out.println(String.format("Number of cells in row  = %d", nor));

            while (iterator.hasNext()) {

                Row currentRow = iterator.next();
                Iterator<Cell> cellIterator = currentRow.iterator();
                
                /*

                while (cellIterator.hasNext()) {

                    Cell currentCell = cellIterator.next();
                    //getCellTypeEnum shown as deprecated for version 3.15
                    //getCellTypeEnum ill be renamed to getCellType starting from version 4.0
                    if (currentCell.getCellType() == CellType.STRING) {
                        System.out.print(currentCell.getStringCellValue() + "--");
                    } else if (currentCell.getCellType() == CellType.NUMERIC) {
                        System.out.print(currentCell.getNumericCellValue() + "--");
                    }

                }
                System.out.println();
                */

            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaserController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaserController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaserController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaserController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LaserController().setVisible(true);
            }
        });
    }
    
    public void setupSystemp(){
        /**
         * Will iterate through each laser and send respective parameters
         * including the paradigm for each channel.
         * Should receive a confirmation from Arduino
         */
    }
    
    public void sendData(String message){
        if(output != null){
            try {
                // Add code to send data
                System.out.println(message);
                output.write(message.getBytes());
                //output.flush();
            } catch (IOException ex) {
                System.out.println("Could not send message...");
                Logger.getLogger(LaserController.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCal1;
    private javax.swing.JToggleButton btnCal2;
    private javax.swing.JToggleButton btnCal3;
    private javax.swing.JToggleButton btnCal4;
    private javax.swing.JToggleButton btnCal5;
    private javax.swing.JToggleButton btnCal6;
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnExec;
    private javax.swing.JToggleButton btnTest1;
    private javax.swing.JToggleButton btnTest2;
    private javax.swing.JToggleButton btnTest3;
    private javax.swing.JToggleButton btnTest4;
    private javax.swing.JToggleButton btnTest5;
    private javax.swing.JToggleButton btnTest6;
    private javax.swing.JButton btnUpload;
    private javax.swing.JTextField dummiesField;
    private javax.swing.JTextField duration1;
    private javax.swing.JTextField duration2;
    private javax.swing.JTextField duration3;
    private javax.swing.JTextField duration4;
    private javax.swing.JTextField duration5;
    private javax.swing.JTextField duration6;
    private javax.swing.JRadioButton enable1;
    private javax.swing.JRadioButton enable2;
    private javax.swing.JRadioButton enable3;
    private javax.swing.JRadioButton enable4;
    private javax.swing.JRadioButton enable5;
    private javax.swing.JRadioButton enable6;
    private javax.swing.JTextField freq1;
    private javax.swing.JTextField freq2;
    private javax.swing.JTextField freq3;
    private javax.swing.JTextField freq4;
    private javax.swing.JTextField freq5;
    private javax.swing.JTextField freq6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel laserPanel1;
    private javax.swing.JPanel laserPanel2;
    private javax.swing.JPanel laserPanel3;
    private javax.swing.JPanel laserPanel4;
    private javax.swing.JPanel laserPanel5;
    private javax.swing.JPanel laserPanel6;
    private javax.swing.JMenuItem menuOpenItem;
    private javax.swing.JTextField nOfScans;
    private javax.swing.JComboBox<String> portDropDown;
    private javax.swing.JTextField trField;
    // End of variables declaration//GEN-END:variables
}
